name: Build & Push Docker Image - Ad Hoc
 
on:
  workflow_dispatch:
 
env:
  DOCKER_IMAGE: co-docker-image-new
  REGISTRY_URL: ghcr.io
  REGISTRY_OWNER: ${{vars.DOCKER_USERNAME}} # Make sure this is all lowercase
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY_URL }}
        username: ${{vars.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PWD }}
 
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_OWNER }}/${{ env.DOCKER_IMAGE }}:latest